// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMNweRR0IE807JY1_DQbZSNlo-apX-B0s',
    appId: '1:11613710443:web:90e34d3571b5ab79b2692e',
    messagingSenderId: '11613710443',
    projectId: 'carbon-db-2a755',
    authDomain: 'carbon-db-2a755.firebaseapp.com',
    storageBucket: 'carbon-db-2a755.firebasestorage.app',
    measurementId: 'G-HENKB778NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxg7diZvN6NZPCoHsoe9m4J6eEAkx1ZFo',
    appId: '1:11613710443:android:20b82424b79d1910b2692e',
    messagingSenderId: '11613710443',
    projectId: 'carbon-db-2a755',
    storageBucket: 'carbon-db-2a755.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-neyapMCR_wSgoN4PYqevuVQSqoivsU',
    appId: '1:11613710443:ios:dae59b34f0dc8a9fb2692e',
    messagingSenderId: '11613710443',
    projectId: 'carbon-db-2a755',
    storageBucket: 'carbon-db-2a755.firebasestorage.app',
    iosBundleId: 'com.example.tizonApp',
  );
}